{"uuid": "1f0f86ce-3380-4769-a0e6-5d0bd5f1a5eb", "children": ["fae0c821-5b61-4b5d-adb2-8539eaae835a"], "befores": [{"name": "authenticated_user", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.InvalidArgumentException: Message: invalid argument: 'url' must be a string\n  (Session info: chrome=126.0.6478.127)\nStacktrace:\n\tGetHandleVerifier [0x00BCC203+27395]\n\t(No symbol) [0x00B63E04]\n\t(No symbol) [0x00A61B7F]\n\t(No symbol) [0x00ADD356]\n\t(No symbol) [0x00AC399C]\n\t(No symbol) [0x00ADCB24]\n\t(No symbol) [0x00AC3736]\n\t(No symbol) [0x00A97541]\n\t(No symbol) [0x00A980BD]\n\tGetHandleVerifier [0x00E83AB3+2876339]\n\tGetHandleVerifier [0x00ED7F7D+3221629]\n\tGetHandleVerifier [0x00C4D674+556916]\n\tGetHandleVerifier [0x00C5478C+585868]\n\t(No symbol) [0x00B6CE44]\n\t(No symbol) [0x00B69858]\n\t(No symbol) [0x00B699F7]\n\t(No symbol) [0x00B5BF4E]\n\tBaseThreadInitThunk [0x7703FCC9+25]\n\tRtlGetAppContainerNamedObjectPath [0x77C980CE+286]\n\tRtlGetAppContainerNamedObjectPath [0x77C9809E+238]\n\n", "trace": "  File \"C:\\Users\\AppzLogic\\Desktop\\Ambitionhire\\venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\AppzLogic\\Desktop\\Ambitionhire\\venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1123, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\AppzLogic\\Desktop\\Ambitionhire\\venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 902, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n                     ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\AppzLogic\\Desktop\\Ambitionhire\\conftest.py\", line 91, in authenticated_user\n    login.get(env)\n  File \"C:\\Users\\AppzLogic\\Desktop\\Ambitionhire\\Pages_Candidate\\base_page.py\", line 20, in get\n    self.driver.get(url)\n  File \"C:\\Users\\AppzLogic\\Desktop\\Ambitionhire\\venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 357, in get\n    self.execute(Command.GET, {\"url\": url})\n  File \"C:\\Users\\AppzLogic\\Desktop\\Ambitionhire\\venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 348, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\AppzLogic\\Desktop\\Ambitionhire\\venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1721632670075, "stop": 1721632670083}], "start": 1721632670075, "stop": 1721632670290}