{"uuid": "0dfaf5cf-c181-4432-ba74-f034895346fa", "children": ["a320e647-bfab-4f06-800f-ec8d76207500"], "befores": [{"name": "driver", "status": "failed", "statusDetails": {"message": "Failed: Chrome driver initialization failed: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location\n\n", "trace": "  File \"C:\\Users\\AppzLogic\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pluggy\\_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\AppzLogic\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1123, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\AppzLogic\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\_pytest\\fixtures.py\", line 895, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"C:\\Users\\AppzLogic\\Desktop\\Ambitionhire\\conftest.py\", line 109, in driver\n    pytest.fail(f\"Chrome driver initialization failed: {e}\")\n  File \"C:\\Users\\AppzLogic\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\_pytest\\outcomes.py\", line 198, in fail\n    raise Failed(msg=reason, pytrace=pytrace)\n"}, "start": 1723095396272, "stop": 1723095405674}], "start": 1723095396272, "stop": 1723095405991}